// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConfigsColumns holds the columns for the "configs" table.
	ConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "configs", Type: field.TypeJSON},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_configs", Type: field.TypeUint64, Unique: true},
	}
	// ConfigsTable holds the schema information for the "configs" table.
	ConfigsTable = &schema.Table{
		Name:       "configs",
		Columns:    ConfigsColumns,
		PrimaryKey: []*schema.Column{ConfigsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "configs_users_configs",
				Columns:    []*schema.Column{ConfigsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TimersColumns holds the columns for the "timers" table.
	TimersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "interval_seconds", Type: field.TypeInt, Default: 300},
		{Name: "message_threshold", Type: field.TypeInt, Default: 1},
		{Name: "message", Type: field.TypeString},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "last_run_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_timers", Type: field.TypeUint64},
	}
	// TimersTable holds the schema information for the "timers" table.
	TimersTable = &schema.Table{
		Name:       "timers",
		Columns:    TimersColumns,
		PrimaryKey: []*schema.Column{TimersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "timers_users_timers",
				Columns:    []*schema.Column{TimersColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// TokensColumns holds the columns for the "tokens" table.
	TokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"access_token", "user_token"}, Default: "access_token"},
		{Name: "token", Type: field.TypeString},
		{Name: "refresh_token", Type: field.TypeString, Nullable: true},
		{Name: "platform", Type: field.TypeEnum, Enums: []string{"twitch"}, Default: "twitch"},
		{Name: "user_tokens", Type: field.TypeUint64},
	}
	// TokensTable holds the schema information for the "tokens" table.
	TokensTable = &schema.Table{
		Name:       "tokens",
		Columns:    TokensColumns,
		PrimaryKey: []*schema.Column{TokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tokens_users_tokens",
				Columns:    []*schema.Column{TokensColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tokens_type_platform_user_tokens",
				Unique:  true,
				Columns: []*schema.Column{TokensColumns[1], TokensColumns[4], TokensColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[0], UsersColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConfigsTable,
		TimersTable,
		TokensTable,
		UsersTable,
	}
)

func init() {
	ConfigsTable.ForeignKeys[0].RefTable = UsersTable
	TimersTable.ForeignKeys[0].RefTable = UsersTable
	TokensTable.ForeignKeys[0].RefTable = UsersTable
}
