// Code generated by ent, DO NOT EDIT.

package timers

import (
	"ItsBagelBot/internal/db/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Timers {
	return predicate.Timers(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Timers {
	return predicate.Timers(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Timers {
	return predicate.Timers(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Timers {
	return predicate.Timers(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Timers {
	return predicate.Timers(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Timers {
	return predicate.Timers(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldName, v))
}

// IntervalSeconds applies equality check predicate on the "interval_seconds" field. It's identical to IntervalSecondsEQ.
func IntervalSeconds(v int) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldIntervalSeconds, v))
}

// MessageThreshold applies equality check predicate on the "message_threshold" field. It's identical to MessageThresholdEQ.
func MessageThreshold(v int) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldMessageThreshold, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldMessage, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldIsActive, v))
}

// LastRunAt applies equality check predicate on the "last_run_at" field. It's identical to LastRunAtEQ.
func LastRunAt(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldLastRunAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Timers {
	return predicate.Timers(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Timers {
	return predicate.Timers(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Timers {
	return predicate.Timers(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Timers {
	return predicate.Timers(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Timers {
	return predicate.Timers(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Timers {
	return predicate.Timers(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Timers {
	return predicate.Timers(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Timers {
	return predicate.Timers(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Timers {
	return predicate.Timers(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Timers {
	return predicate.Timers(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Timers {
	return predicate.Timers(sql.FieldContainsFold(FieldName, v))
}

// IntervalSecondsEQ applies the EQ predicate on the "interval_seconds" field.
func IntervalSecondsEQ(v int) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsNEQ applies the NEQ predicate on the "interval_seconds" field.
func IntervalSecondsNEQ(v int) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsIn applies the In predicate on the "interval_seconds" field.
func IntervalSecondsIn(vs ...int) predicate.Timers {
	return predicate.Timers(sql.FieldIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsNotIn applies the NotIn predicate on the "interval_seconds" field.
func IntervalSecondsNotIn(vs ...int) predicate.Timers {
	return predicate.Timers(sql.FieldNotIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsGT applies the GT predicate on the "interval_seconds" field.
func IntervalSecondsGT(v int) predicate.Timers {
	return predicate.Timers(sql.FieldGT(FieldIntervalSeconds, v))
}

// IntervalSecondsGTE applies the GTE predicate on the "interval_seconds" field.
func IntervalSecondsGTE(v int) predicate.Timers {
	return predicate.Timers(sql.FieldGTE(FieldIntervalSeconds, v))
}

// IntervalSecondsLT applies the LT predicate on the "interval_seconds" field.
func IntervalSecondsLT(v int) predicate.Timers {
	return predicate.Timers(sql.FieldLT(FieldIntervalSeconds, v))
}

// IntervalSecondsLTE applies the LTE predicate on the "interval_seconds" field.
func IntervalSecondsLTE(v int) predicate.Timers {
	return predicate.Timers(sql.FieldLTE(FieldIntervalSeconds, v))
}

// MessageThresholdEQ applies the EQ predicate on the "message_threshold" field.
func MessageThresholdEQ(v int) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldMessageThreshold, v))
}

// MessageThresholdNEQ applies the NEQ predicate on the "message_threshold" field.
func MessageThresholdNEQ(v int) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldMessageThreshold, v))
}

// MessageThresholdIn applies the In predicate on the "message_threshold" field.
func MessageThresholdIn(vs ...int) predicate.Timers {
	return predicate.Timers(sql.FieldIn(FieldMessageThreshold, vs...))
}

// MessageThresholdNotIn applies the NotIn predicate on the "message_threshold" field.
func MessageThresholdNotIn(vs ...int) predicate.Timers {
	return predicate.Timers(sql.FieldNotIn(FieldMessageThreshold, vs...))
}

// MessageThresholdGT applies the GT predicate on the "message_threshold" field.
func MessageThresholdGT(v int) predicate.Timers {
	return predicate.Timers(sql.FieldGT(FieldMessageThreshold, v))
}

// MessageThresholdGTE applies the GTE predicate on the "message_threshold" field.
func MessageThresholdGTE(v int) predicate.Timers {
	return predicate.Timers(sql.FieldGTE(FieldMessageThreshold, v))
}

// MessageThresholdLT applies the LT predicate on the "message_threshold" field.
func MessageThresholdLT(v int) predicate.Timers {
	return predicate.Timers(sql.FieldLT(FieldMessageThreshold, v))
}

// MessageThresholdLTE applies the LTE predicate on the "message_threshold" field.
func MessageThresholdLTE(v int) predicate.Timers {
	return predicate.Timers(sql.FieldLTE(FieldMessageThreshold, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.Timers {
	return predicate.Timers(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.Timers {
	return predicate.Timers(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.Timers {
	return predicate.Timers(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.Timers {
	return predicate.Timers(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.Timers {
	return predicate.Timers(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.Timers {
	return predicate.Timers(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.Timers {
	return predicate.Timers(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.Timers {
	return predicate.Timers(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.Timers {
	return predicate.Timers(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.Timers {
	return predicate.Timers(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.Timers {
	return predicate.Timers(sql.FieldContainsFold(FieldMessage, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldIsActive, v))
}

// LastRunAtEQ applies the EQ predicate on the "last_run_at" field.
func LastRunAtEQ(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldLastRunAt, v))
}

// LastRunAtNEQ applies the NEQ predicate on the "last_run_at" field.
func LastRunAtNEQ(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldLastRunAt, v))
}

// LastRunAtIn applies the In predicate on the "last_run_at" field.
func LastRunAtIn(vs ...time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldIn(FieldLastRunAt, vs...))
}

// LastRunAtNotIn applies the NotIn predicate on the "last_run_at" field.
func LastRunAtNotIn(vs ...time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldNotIn(FieldLastRunAt, vs...))
}

// LastRunAtGT applies the GT predicate on the "last_run_at" field.
func LastRunAtGT(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldGT(FieldLastRunAt, v))
}

// LastRunAtGTE applies the GTE predicate on the "last_run_at" field.
func LastRunAtGTE(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldGTE(FieldLastRunAt, v))
}

// LastRunAtLT applies the LT predicate on the "last_run_at" field.
func LastRunAtLT(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldLT(FieldLastRunAt, v))
}

// LastRunAtLTE applies the LTE predicate on the "last_run_at" field.
func LastRunAtLTE(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldLTE(FieldLastRunAt, v))
}

// LastRunAtIsNil applies the IsNil predicate on the "last_run_at" field.
func LastRunAtIsNil() predicate.Timers {
	return predicate.Timers(sql.FieldIsNull(FieldLastRunAt))
}

// LastRunAtNotNil applies the NotNil predicate on the "last_run_at" field.
func LastRunAtNotNil() predicate.Timers {
	return predicate.Timers(sql.FieldNotNull(FieldLastRunAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Timers {
	return predicate.Timers(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.Timers {
	return predicate.Timers(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.User) predicate.Timers {
	return predicate.Timers(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Timers) predicate.Timers {
	return predicate.Timers(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Timers) predicate.Timers {
	return predicate.Timers(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Timers) predicate.Timers {
	return predicate.Timers(sql.NotPredicates(p))
}
