// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Configs is the predicate function for configs builders.
type Configs func(*sql.Selector)

// Timers is the predicate function for timers builders.
type Timers func(*sql.Selector)

// Tokens is the predicate function for tokens builders.
type Tokens func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
