// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"ItsBagelBot/internal/db/ent/migrate"

	"ItsBagelBot/internal/db/ent/configs"
	"ItsBagelBot/internal/db/ent/timers"
	"ItsBagelBot/internal/db/ent/tokens"
	"ItsBagelBot/internal/db/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Configs is the client for interacting with the Configs builders.
	Configs *ConfigsClient
	// Timers is the client for interacting with the Timers builders.
	Timers *TimersClient
	// Tokens is the client for interacting with the Tokens builders.
	Tokens *TokensClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Configs = NewConfigsClient(c.config)
	c.Timers = NewTimersClient(c.config)
	c.Tokens = NewTokensClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Configs: NewConfigsClient(cfg),
		Timers:  NewTimersClient(cfg),
		Tokens:  NewTokensClient(cfg),
		User:    NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:     ctx,
		config:  cfg,
		Configs: NewConfigsClient(cfg),
		Timers:  NewTimersClient(cfg),
		Tokens:  NewTokensClient(cfg),
		User:    NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Configs.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Configs.Use(hooks...)
	c.Timers.Use(hooks...)
	c.Tokens.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Configs.Intercept(interceptors...)
	c.Timers.Intercept(interceptors...)
	c.Tokens.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ConfigsMutation:
		return c.Configs.mutate(ctx, m)
	case *TimersMutation:
		return c.Timers.mutate(ctx, m)
	case *TokensMutation:
		return c.Tokens.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ConfigsClient is a client for the Configs schema.
type ConfigsClient struct {
	config
}

// NewConfigsClient returns a client for the Configs from the given config.
func NewConfigsClient(c config) *ConfigsClient {
	return &ConfigsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `configs.Hooks(f(g(h())))`.
func (c *ConfigsClient) Use(hooks ...Hook) {
	c.hooks.Configs = append(c.hooks.Configs, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `configs.Intercept(f(g(h())))`.
func (c *ConfigsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Configs = append(c.inters.Configs, interceptors...)
}

// Create returns a builder for creating a Configs entity.
func (c *ConfigsClient) Create() *ConfigsCreate {
	mutation := newConfigsMutation(c.config, OpCreate)
	return &ConfigsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Configs entities.
func (c *ConfigsClient) CreateBulk(builders ...*ConfigsCreate) *ConfigsCreateBulk {
	return &ConfigsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ConfigsClient) MapCreateBulk(slice any, setFunc func(*ConfigsCreate, int)) *ConfigsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ConfigsCreateBulk{err: fmt.Errorf("calling to ConfigsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ConfigsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ConfigsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Configs.
func (c *ConfigsClient) Update() *ConfigsUpdate {
	mutation := newConfigsMutation(c.config, OpUpdate)
	return &ConfigsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ConfigsClient) UpdateOne(_m *Configs) *ConfigsUpdateOne {
	mutation := newConfigsMutation(c.config, OpUpdateOne, withConfigs(_m))
	return &ConfigsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ConfigsClient) UpdateOneID(id int) *ConfigsUpdateOne {
	mutation := newConfigsMutation(c.config, OpUpdateOne, withConfigsID(id))
	return &ConfigsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Configs.
func (c *ConfigsClient) Delete() *ConfigsDelete {
	mutation := newConfigsMutation(c.config, OpDelete)
	return &ConfigsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ConfigsClient) DeleteOne(_m *Configs) *ConfigsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ConfigsClient) DeleteOneID(id int) *ConfigsDeleteOne {
	builder := c.Delete().Where(configs.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ConfigsDeleteOne{builder}
}

// Query returns a query builder for Configs.
func (c *ConfigsClient) Query() *ConfigsQuery {
	return &ConfigsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeConfigs},
		inters: c.Interceptors(),
	}
}

// Get returns a Configs entity by its id.
func (c *ConfigsClient) Get(ctx context.Context, id int) (*Configs, error) {
	return c.Query().Where(configs.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ConfigsClient) GetX(ctx context.Context, id int) *Configs {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a Configs.
func (c *ConfigsClient) QueryUsers(_m *Configs) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(configs.Table, configs.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, configs.UsersTable, configs.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ConfigsClient) Hooks() []Hook {
	return c.hooks.Configs
}

// Interceptors returns the client interceptors.
func (c *ConfigsClient) Interceptors() []Interceptor {
	return c.inters.Configs
}

func (c *ConfigsClient) mutate(ctx context.Context, m *ConfigsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ConfigsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ConfigsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ConfigsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ConfigsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Configs mutation op: %q", m.Op())
	}
}

// TimersClient is a client for the Timers schema.
type TimersClient struct {
	config
}

// NewTimersClient returns a client for the Timers from the given config.
func NewTimersClient(c config) *TimersClient {
	return &TimersClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `timers.Hooks(f(g(h())))`.
func (c *TimersClient) Use(hooks ...Hook) {
	c.hooks.Timers = append(c.hooks.Timers, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `timers.Intercept(f(g(h())))`.
func (c *TimersClient) Intercept(interceptors ...Interceptor) {
	c.inters.Timers = append(c.inters.Timers, interceptors...)
}

// Create returns a builder for creating a Timers entity.
func (c *TimersClient) Create() *TimersCreate {
	mutation := newTimersMutation(c.config, OpCreate)
	return &TimersCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Timers entities.
func (c *TimersClient) CreateBulk(builders ...*TimersCreate) *TimersCreateBulk {
	return &TimersCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TimersClient) MapCreateBulk(slice any, setFunc func(*TimersCreate, int)) *TimersCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TimersCreateBulk{err: fmt.Errorf("calling to TimersClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TimersCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TimersCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Timers.
func (c *TimersClient) Update() *TimersUpdate {
	mutation := newTimersMutation(c.config, OpUpdate)
	return &TimersUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TimersClient) UpdateOne(_m *Timers) *TimersUpdateOne {
	mutation := newTimersMutation(c.config, OpUpdateOne, withTimers(_m))
	return &TimersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TimersClient) UpdateOneID(id int) *TimersUpdateOne {
	mutation := newTimersMutation(c.config, OpUpdateOne, withTimersID(id))
	return &TimersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Timers.
func (c *TimersClient) Delete() *TimersDelete {
	mutation := newTimersMutation(c.config, OpDelete)
	return &TimersDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TimersClient) DeleteOne(_m *Timers) *TimersDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TimersClient) DeleteOneID(id int) *TimersDeleteOne {
	builder := c.Delete().Where(timers.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TimersDeleteOne{builder}
}

// Query returns a query builder for Timers.
func (c *TimersClient) Query() *TimersQuery {
	return &TimersQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTimers},
		inters: c.Interceptors(),
	}
}

// Get returns a Timers entity by its id.
func (c *TimersClient) Get(ctx context.Context, id int) (*Timers, error) {
	return c.Query().Where(timers.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TimersClient) GetX(ctx context.Context, id int) *Timers {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a Timers.
func (c *TimersClient) QueryUsers(_m *Timers) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(timers.Table, timers.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, timers.UsersTable, timers.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TimersClient) Hooks() []Hook {
	return c.hooks.Timers
}

// Interceptors returns the client interceptors.
func (c *TimersClient) Interceptors() []Interceptor {
	return c.inters.Timers
}

func (c *TimersClient) mutate(ctx context.Context, m *TimersMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TimersCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TimersUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TimersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TimersDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Timers mutation op: %q", m.Op())
	}
}

// TokensClient is a client for the Tokens schema.
type TokensClient struct {
	config
}

// NewTokensClient returns a client for the Tokens from the given config.
func NewTokensClient(c config) *TokensClient {
	return &TokensClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tokens.Hooks(f(g(h())))`.
func (c *TokensClient) Use(hooks ...Hook) {
	c.hooks.Tokens = append(c.hooks.Tokens, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tokens.Intercept(f(g(h())))`.
func (c *TokensClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tokens = append(c.inters.Tokens, interceptors...)
}

// Create returns a builder for creating a Tokens entity.
func (c *TokensClient) Create() *TokensCreate {
	mutation := newTokensMutation(c.config, OpCreate)
	return &TokensCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tokens entities.
func (c *TokensClient) CreateBulk(builders ...*TokensCreate) *TokensCreateBulk {
	return &TokensCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TokensClient) MapCreateBulk(slice any, setFunc func(*TokensCreate, int)) *TokensCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TokensCreateBulk{err: fmt.Errorf("calling to TokensClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TokensCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TokensCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tokens.
func (c *TokensClient) Update() *TokensUpdate {
	mutation := newTokensMutation(c.config, OpUpdate)
	return &TokensUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TokensClient) UpdateOne(_m *Tokens) *TokensUpdateOne {
	mutation := newTokensMutation(c.config, OpUpdateOne, withTokens(_m))
	return &TokensUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TokensClient) UpdateOneID(id int) *TokensUpdateOne {
	mutation := newTokensMutation(c.config, OpUpdateOne, withTokensID(id))
	return &TokensUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tokens.
func (c *TokensClient) Delete() *TokensDelete {
	mutation := newTokensMutation(c.config, OpDelete)
	return &TokensDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TokensClient) DeleteOne(_m *Tokens) *TokensDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TokensClient) DeleteOneID(id int) *TokensDeleteOne {
	builder := c.Delete().Where(tokens.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TokensDeleteOne{builder}
}

// Query returns a query builder for Tokens.
func (c *TokensClient) Query() *TokensQuery {
	return &TokensQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTokens},
		inters: c.Interceptors(),
	}
}

// Get returns a Tokens entity by its id.
func (c *TokensClient) Get(ctx context.Context, id int) (*Tokens, error) {
	return c.Query().Where(tokens.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TokensClient) GetX(ctx context.Context, id int) *Tokens {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the users edge of a Tokens.
func (c *TokensClient) QueryUsers(_m *Tokens) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tokens.Table, tokens.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tokens.UsersTable, tokens.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TokensClient) Hooks() []Hook {
	return c.hooks.Tokens
}

// Interceptors returns the client interceptors.
func (c *TokensClient) Interceptors() []Interceptor {
	return c.inters.Tokens
}

func (c *TokensClient) mutate(ctx context.Context, m *TokensMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TokensCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TokensUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TokensUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TokensDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tokens mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uint64) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uint64) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uint64) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uint64) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryConfigs queries the configs edge of a User.
func (c *UserClient) QueryConfigs(_m *User) *ConfigsQuery {
	query := (&ConfigsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(configs.Table, configs.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, user.ConfigsTable, user.ConfigsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTokens queries the tokens edge of a User.
func (c *UserClient) QueryTokens(_m *User) *TokensQuery {
	query := (&TokensClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(tokens.Table, tokens.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.TokensTable, user.TokensColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTimers queries the timers edge of a User.
func (c *UserClient) QueryTimers(_m *User) *TimersQuery {
	query := (&TimersClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(timers.Table, timers.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.TimersTable, user.TimersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Configs, Timers, Tokens, User []ent.Hook
	}
	inters struct {
		Configs, Timers, Tokens, User []ent.Interceptor
	}
)
