// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/configs"
	"ItsBagelBot/internal/db/ent/user"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Configs is the model entity for the Configs schema.
type Configs struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Configs holds the value of the "configs" field.
	Configs []uint8 `json:"configs,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConfigsQuery when eager-loading is set.
	Edges        ConfigsEdges `json:"edges"`
	user_configs *uint64
	selectValues sql.SelectValues
}

// ConfigsEdges holds the relations/edges for other nodes in the graph.
type ConfigsEdges struct {
	// Users holds the value of the users edge.
	Users *User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConfigsEdges) UsersOrErr() (*User, error) {
	if e.Users != nil {
		return e.Users, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Configs) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case configs.FieldConfigs:
			values[i] = new([]byte)
		case configs.FieldID:
			values[i] = new(sql.NullInt64)
		case configs.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case configs.ForeignKeys[0]: // user_configs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Configs fields.
func (_m *Configs) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case configs.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case configs.FieldConfigs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field configs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Configs); err != nil {
					return fmt.Errorf("unmarshal field configs: %w", err)
				}
			}
		case configs.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case configs.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_configs", value)
			} else if value.Valid {
				_m.user_configs = new(uint64)
				*_m.user_configs = uint64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Configs.
// This includes values selected through modifiers, order, etc.
func (_m *Configs) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Configs entity.
func (_m *Configs) QueryUsers() *UserQuery {
	return NewConfigsClient(_m.config).QueryUsers(_m)
}

// Update returns a builder for updating this Configs.
// Note that you need to call Configs.Unwrap() before calling this method if this Configs
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Configs) Update() *ConfigsUpdateOne {
	return NewConfigsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Configs entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Configs) Unwrap() *Configs {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Configs is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Configs) String() string {
	var builder strings.Builder
	builder.WriteString("Configs(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("configs=")
	builder.WriteString(fmt.Sprintf("%v", _m.Configs))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ConfigsSlice is a parsable slice of Configs.
type ConfigsSlice []*Configs
