// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/configs"
	"ItsBagelBot/internal/db/ent/predicate"
	"ItsBagelBot/internal/db/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ConfigsUpdate is the builder for updating Configs entities.
type ConfigsUpdate struct {
	config
	hooks    []Hook
	mutation *ConfigsMutation
}

// Where appends a list predicates to the ConfigsUpdate builder.
func (_u *ConfigsUpdate) Where(ps ...predicate.Configs) *ConfigsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConfigs sets the "configs" field.
func (_u *ConfigsUpdate) SetConfigs(v []uint8) *ConfigsUpdate {
	_u.mutation.SetConfigs(v)
	return _u
}

// AppendConfigs appends value to the "configs" field.
func (_u *ConfigsUpdate) AppendConfigs(v []uint8) *ConfigsUpdate {
	_u.mutation.AppendConfigs(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConfigsUpdate) SetUpdatedAt(v time.Time) *ConfigsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *ConfigsUpdate) SetUsersID(id uint64) *ConfigsUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *ConfigsUpdate) SetUsers(v *User) *ConfigsUpdate {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the ConfigsMutation object of the builder.
func (_u *ConfigsUpdate) Mutation() *ConfigsMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *ConfigsUpdate) ClearUsers() *ConfigsUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConfigsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConfigsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConfigsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := configs.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigsUpdate) check() error {
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Configs.users"`)
	}
	return nil
}

func (_u *ConfigsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configs.Table, configs.Columns, sqlgraph.NewFieldSpec(configs.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Configs(); ok {
		_spec.SetField(configs.FieldConfigs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfigs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, configs.FieldConfigs, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(configs.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   configs.UsersTable,
			Columns: []string{configs.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   configs.UsersTable,
			Columns: []string{configs.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configs.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConfigsUpdateOne is the builder for updating a single Configs entity.
type ConfigsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConfigsMutation
}

// SetConfigs sets the "configs" field.
func (_u *ConfigsUpdateOne) SetConfigs(v []uint8) *ConfigsUpdateOne {
	_u.mutation.SetConfigs(v)
	return _u
}

// AppendConfigs appends value to the "configs" field.
func (_u *ConfigsUpdateOne) AppendConfigs(v []uint8) *ConfigsUpdateOne {
	_u.mutation.AppendConfigs(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConfigsUpdateOne) SetUpdatedAt(v time.Time) *ConfigsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *ConfigsUpdateOne) SetUsersID(id uint64) *ConfigsUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *ConfigsUpdateOne) SetUsers(v *User) *ConfigsUpdateOne {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the ConfigsMutation object of the builder.
func (_u *ConfigsUpdateOne) Mutation() *ConfigsMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *ConfigsUpdateOne) ClearUsers() *ConfigsUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// Where appends a list predicates to the ConfigsUpdate builder.
func (_u *ConfigsUpdateOne) Where(ps ...predicate.Configs) *ConfigsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConfigsUpdateOne) Select(field string, fields ...string) *ConfigsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Configs entity.
func (_u *ConfigsUpdateOne) Save(ctx context.Context) (*Configs, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConfigsUpdateOne) SaveX(ctx context.Context) *Configs {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConfigsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConfigsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConfigsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := configs.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConfigsUpdateOne) check() error {
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Configs.users"`)
	}
	return nil
}

func (_u *ConfigsUpdateOne) sqlSave(ctx context.Context) (_node *Configs, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(configs.Table, configs.Columns, sqlgraph.NewFieldSpec(configs.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Configs.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, configs.FieldID)
		for _, f := range fields {
			if !configs.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != configs.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Configs(); ok {
		_spec.SetField(configs.FieldConfigs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedConfigs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, configs.FieldConfigs, value)
		})
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(configs.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   configs.UsersTable,
			Columns: []string{configs.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   configs.UsersTable,
			Columns: []string{configs.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Configs{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{configs.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
