// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/configs"
	"ItsBagelBot/internal/db/ent/schema"
	"ItsBagelBot/internal/db/ent/timers"
	"ItsBagelBot/internal/db/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	configsFields := schema.Configs{}.Fields()
	_ = configsFields
	// configsDescUpdatedAt is the schema descriptor for updated_at field.
	configsDescUpdatedAt := configsFields[1].Descriptor()
	// configs.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	configs.DefaultUpdatedAt = configsDescUpdatedAt.Default.(func() time.Time)
	// configs.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	configs.UpdateDefaultUpdatedAt = configsDescUpdatedAt.UpdateDefault.(func() time.Time)
	timersFields := schema.Timers{}.Fields()
	_ = timersFields
	// timersDescName is the schema descriptor for name field.
	timersDescName := timersFields[0].Descriptor()
	// timers.NameValidator is a validator for the "name" field. It is called by the builders before save.
	timers.NameValidator = timersDescName.Validators[0].(func(string) error)
	// timersDescIntervalSeconds is the schema descriptor for interval_seconds field.
	timersDescIntervalSeconds := timersFields[1].Descriptor()
	// timers.DefaultIntervalSeconds holds the default value on creation for the interval_seconds field.
	timers.DefaultIntervalSeconds = timersDescIntervalSeconds.Default.(int)
	// timersDescMessageThreshold is the schema descriptor for message_threshold field.
	timersDescMessageThreshold := timersFields[2].Descriptor()
	// timers.DefaultMessageThreshold holds the default value on creation for the message_threshold field.
	timers.DefaultMessageThreshold = timersDescMessageThreshold.Default.(int)
	// timersDescMessage is the schema descriptor for message field.
	timersDescMessage := timersFields[3].Descriptor()
	// timers.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	timers.MessageValidator = timersDescMessage.Validators[0].(func(string) error)
	// timersDescIsActive is the schema descriptor for is_active field.
	timersDescIsActive := timersFields[4].Descriptor()
	// timers.DefaultIsActive holds the default value on creation for the is_active field.
	timers.DefaultIsActive = timersDescIsActive.Default.(bool)
	// timersDescLastRunAt is the schema descriptor for last_run_at field.
	timersDescLastRunAt := timersFields[5].Descriptor()
	// timers.DefaultLastRunAt holds the default value on creation for the last_run_at field.
	timers.DefaultLastRunAt = timersDescLastRunAt.Default.(time.Time)
	// timersDescCreatedAt is the schema descriptor for created_at field.
	timersDescCreatedAt := timersFields[6].Descriptor()
	// timers.DefaultCreatedAt holds the default value on creation for the created_at field.
	timers.DefaultCreatedAt = timersDescCreatedAt.Default.(func() time.Time)
	// timersDescUpdatedAt is the schema descriptor for updated_at field.
	timersDescUpdatedAt := timersFields[7].Descriptor()
	// timers.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	timers.DefaultUpdatedAt = timersDescUpdatedAt.Default.(func() time.Time)
	// timers.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	timers.UpdateDefaultUpdatedAt = timersDescUpdatedAt.UpdateDefault.(func() time.Time)
	tokensFields := schema.Tokens{}.Fields()
	_ = tokensFields
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[2].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescIsActive is the schema descriptor for is_active field.
	userDescIsActive := userFields[3].Descriptor()
	// user.DefaultIsActive holds the default value on creation for the is_active field.
	user.DefaultIsActive = userDescIsActive.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
