// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/predicate"
	"ItsBagelBot/internal/db/ent/timers"
	"ItsBagelBot/internal/db/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimersUpdate is the builder for updating Timers entities.
type TimersUpdate struct {
	config
	hooks    []Hook
	mutation *TimersMutation
}

// Where appends a list predicates to the TimersUpdate builder.
func (_u *TimersUpdate) Where(ps ...predicate.Timers) *TimersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TimersUpdate) SetName(v string) *TimersUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TimersUpdate) SetNillableName(v *string) *TimersUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *TimersUpdate) SetIntervalSeconds(v int) *TimersUpdate {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *TimersUpdate) SetNillableIntervalSeconds(v *int) *TimersUpdate {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *TimersUpdate) AddIntervalSeconds(v int) *TimersUpdate {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// SetMessageThreshold sets the "message_threshold" field.
func (_u *TimersUpdate) SetMessageThreshold(v int) *TimersUpdate {
	_u.mutation.ResetMessageThreshold()
	_u.mutation.SetMessageThreshold(v)
	return _u
}

// SetNillableMessageThreshold sets the "message_threshold" field if the given value is not nil.
func (_u *TimersUpdate) SetNillableMessageThreshold(v *int) *TimersUpdate {
	if v != nil {
		_u.SetMessageThreshold(*v)
	}
	return _u
}

// AddMessageThreshold adds value to the "message_threshold" field.
func (_u *TimersUpdate) AddMessageThreshold(v int) *TimersUpdate {
	_u.mutation.AddMessageThreshold(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *TimersUpdate) SetMessage(v string) *TimersUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *TimersUpdate) SetNillableMessage(v *string) *TimersUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TimersUpdate) SetIsActive(v bool) *TimersUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TimersUpdate) SetNillableIsActive(v *bool) *TimersUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *TimersUpdate) SetLastRunAt(v time.Time) *TimersUpdate {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *TimersUpdate) SetNillableLastRunAt(v *time.Time) *TimersUpdate {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *TimersUpdate) ClearLastRunAt() *TimersUpdate {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TimersUpdate) SetCreatedAt(v time.Time) *TimersUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TimersUpdate) SetNillableCreatedAt(v *time.Time) *TimersUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TimersUpdate) SetUpdatedAt(v time.Time) *TimersUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *TimersUpdate) SetUsersID(id uint64) *TimersUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *TimersUpdate) SetUsers(v *User) *TimersUpdate {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the TimersMutation object of the builder.
func (_u *TimersUpdate) Mutation() *TimersMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *TimersUpdate) ClearUsers() *TimersUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TimersUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TimersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TimersUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := timers.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimersUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := timers.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Timers.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := timers.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Timers.message": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Timers.users"`)
	}
	return nil
}

func (_u *TimersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timers.Table, timers.Columns, sqlgraph.NewFieldSpec(timers.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(timers.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(timers.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(timers.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MessageThreshold(); ok {
		_spec.SetField(timers.FieldMessageThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageThreshold(); ok {
		_spec.AddField(timers.FieldMessageThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(timers.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(timers.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(timers.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(timers.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(timers.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(timers.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timers.UsersTable,
			Columns: []string{timers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timers.UsersTable,
			Columns: []string{timers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TimersUpdateOne is the builder for updating a single Timers entity.
type TimersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TimersMutation
}

// SetName sets the "name" field.
func (_u *TimersUpdateOne) SetName(v string) *TimersUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TimersUpdateOne) SetNillableName(v *string) *TimersUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_u *TimersUpdateOne) SetIntervalSeconds(v int) *TimersUpdateOne {
	_u.mutation.ResetIntervalSeconds()
	_u.mutation.SetIntervalSeconds(v)
	return _u
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_u *TimersUpdateOne) SetNillableIntervalSeconds(v *int) *TimersUpdateOne {
	if v != nil {
		_u.SetIntervalSeconds(*v)
	}
	return _u
}

// AddIntervalSeconds adds value to the "interval_seconds" field.
func (_u *TimersUpdateOne) AddIntervalSeconds(v int) *TimersUpdateOne {
	_u.mutation.AddIntervalSeconds(v)
	return _u
}

// SetMessageThreshold sets the "message_threshold" field.
func (_u *TimersUpdateOne) SetMessageThreshold(v int) *TimersUpdateOne {
	_u.mutation.ResetMessageThreshold()
	_u.mutation.SetMessageThreshold(v)
	return _u
}

// SetNillableMessageThreshold sets the "message_threshold" field if the given value is not nil.
func (_u *TimersUpdateOne) SetNillableMessageThreshold(v *int) *TimersUpdateOne {
	if v != nil {
		_u.SetMessageThreshold(*v)
	}
	return _u
}

// AddMessageThreshold adds value to the "message_threshold" field.
func (_u *TimersUpdateOne) AddMessageThreshold(v int) *TimersUpdateOne {
	_u.mutation.AddMessageThreshold(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *TimersUpdateOne) SetMessage(v string) *TimersUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *TimersUpdateOne) SetNillableMessage(v *string) *TimersUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *TimersUpdateOne) SetIsActive(v bool) *TimersUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *TimersUpdateOne) SetNillableIsActive(v *bool) *TimersUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *TimersUpdateOne) SetLastRunAt(v time.Time) *TimersUpdateOne {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *TimersUpdateOne) SetNillableLastRunAt(v *time.Time) *TimersUpdateOne {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *TimersUpdateOne) ClearLastRunAt() *TimersUpdateOne {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TimersUpdateOne) SetCreatedAt(v time.Time) *TimersUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TimersUpdateOne) SetNillableCreatedAt(v *time.Time) *TimersUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TimersUpdateOne) SetUpdatedAt(v time.Time) *TimersUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *TimersUpdateOne) SetUsersID(id uint64) *TimersUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *TimersUpdateOne) SetUsers(v *User) *TimersUpdateOne {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the TimersMutation object of the builder.
func (_u *TimersUpdateOne) Mutation() *TimersMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *TimersUpdateOne) ClearUsers() *TimersUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// Where appends a list predicates to the TimersUpdate builder.
func (_u *TimersUpdateOne) Where(ps ...predicate.Timers) *TimersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TimersUpdateOne) Select(field string, fields ...string) *TimersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Timers entity.
func (_u *TimersUpdateOne) Save(ctx context.Context) (*Timers, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimersUpdateOne) SaveX(ctx context.Context) *Timers {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TimersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TimersUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := timers.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimersUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := timers.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Timers.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := timers.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Timers.message": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Timers.users"`)
	}
	return nil
}

func (_u *TimersUpdateOne) sqlSave(ctx context.Context) (_node *Timers, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timers.Table, timers.Columns, sqlgraph.NewFieldSpec(timers.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Timers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, timers.FieldID)
		for _, f := range fields {
			if !timers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != timers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(timers.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IntervalSeconds(); ok {
		_spec.SetField(timers.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(timers.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MessageThreshold(); ok {
		_spec.SetField(timers.FieldMessageThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMessageThreshold(); ok {
		_spec.AddField(timers.FieldMessageThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(timers.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(timers.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(timers.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(timers.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(timers.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(timers.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timers.UsersTable,
			Columns: []string{timers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timers.UsersTable,
			Columns: []string{timers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Timers{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
