// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/timers"
	"ItsBagelBot/internal/db/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TimersCreate is the builder for creating a Timers entity.
type TimersCreate struct {
	config
	mutation *TimersMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TimersCreate) SetName(v string) *TimersCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (_c *TimersCreate) SetIntervalSeconds(v int) *TimersCreate {
	_c.mutation.SetIntervalSeconds(v)
	return _c
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (_c *TimersCreate) SetNillableIntervalSeconds(v *int) *TimersCreate {
	if v != nil {
		_c.SetIntervalSeconds(*v)
	}
	return _c
}

// SetMessageThreshold sets the "message_threshold" field.
func (_c *TimersCreate) SetMessageThreshold(v int) *TimersCreate {
	_c.mutation.SetMessageThreshold(v)
	return _c
}

// SetNillableMessageThreshold sets the "message_threshold" field if the given value is not nil.
func (_c *TimersCreate) SetNillableMessageThreshold(v *int) *TimersCreate {
	if v != nil {
		_c.SetMessageThreshold(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *TimersCreate) SetMessage(v string) *TimersCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *TimersCreate) SetIsActive(v bool) *TimersCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *TimersCreate) SetNillableIsActive(v *bool) *TimersCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetLastRunAt sets the "last_run_at" field.
func (_c *TimersCreate) SetLastRunAt(v time.Time) *TimersCreate {
	_c.mutation.SetLastRunAt(v)
	return _c
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_c *TimersCreate) SetNillableLastRunAt(v *time.Time) *TimersCreate {
	if v != nil {
		_c.SetLastRunAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TimersCreate) SetCreatedAt(v time.Time) *TimersCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TimersCreate) SetNillableCreatedAt(v *time.Time) *TimersCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TimersCreate) SetUpdatedAt(v time.Time) *TimersCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TimersCreate) SetNillableUpdatedAt(v *time.Time) *TimersCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_c *TimersCreate) SetUsersID(id uint64) *TimersCreate {
	_c.mutation.SetUsersID(id)
	return _c
}

// SetUsers sets the "users" edge to the User entity.
func (_c *TimersCreate) SetUsers(v *User) *TimersCreate {
	return _c.SetUsersID(v.ID)
}

// Mutation returns the TimersMutation object of the builder.
func (_c *TimersCreate) Mutation() *TimersMutation {
	return _c.mutation
}

// Save creates the Timers in the database.
func (_c *TimersCreate) Save(ctx context.Context) (*Timers, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TimersCreate) SaveX(ctx context.Context) *Timers {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimersCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimersCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TimersCreate) defaults() {
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		v := timers.DefaultIntervalSeconds
		_c.mutation.SetIntervalSeconds(v)
	}
	if _, ok := _c.mutation.MessageThreshold(); !ok {
		v := timers.DefaultMessageThreshold
		_c.mutation.SetMessageThreshold(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := timers.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.LastRunAt(); !ok {
		v := timers.DefaultLastRunAt
		_c.mutation.SetLastRunAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := timers.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := timers.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TimersCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Timers.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := timers.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Timers.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntervalSeconds(); !ok {
		return &ValidationError{Name: "interval_seconds", err: errors.New(`ent: missing required field "Timers.interval_seconds"`)}
	}
	if _, ok := _c.mutation.MessageThreshold(); !ok {
		return &ValidationError{Name: "message_threshold", err: errors.New(`ent: missing required field "Timers.message_threshold"`)}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "Timers.message"`)}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := timers.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Timers.message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Timers.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Timers.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Timers.updated_at"`)}
	}
	if len(_c.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "users", err: errors.New(`ent: missing required edge "Timers.users"`)}
	}
	return nil
}

func (_c *TimersCreate) sqlSave(ctx context.Context) (*Timers, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TimersCreate) createSpec() (*Timers, *sqlgraph.CreateSpec) {
	var (
		_node = &Timers{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(timers.Table, sqlgraph.NewFieldSpec(timers.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(timers.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IntervalSeconds(); ok {
		_spec.SetField(timers.FieldIntervalSeconds, field.TypeInt, value)
		_node.IntervalSeconds = value
	}
	if value, ok := _c.mutation.MessageThreshold(); ok {
		_spec.SetField(timers.FieldMessageThreshold, field.TypeInt, value)
		_node.MessageThreshold = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(timers.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(timers.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.LastRunAt(); ok {
		_spec.SetField(timers.FieldLastRunAt, field.TypeTime, value)
		_node.LastRunAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(timers.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(timers.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   timers.UsersTable,
			Columns: []string{timers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_timers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TimersCreateBulk is the builder for creating many Timers entities in bulk.
type TimersCreateBulk struct {
	config
	err      error
	builders []*TimersCreate
}

// Save creates the Timers entities in the database.
func (_c *TimersCreateBulk) Save(ctx context.Context) ([]*Timers, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Timers, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimersMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TimersCreateBulk) SaveX(ctx context.Context) []*Timers {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimersCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimersCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
