// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/timers"
	"ItsBagelBot/internal/db/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Timers is the model entity for the Timers schema.
type Timers struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// IntervalSeconds holds the value of the "interval_seconds" field.
	IntervalSeconds int `json:"interval_seconds,omitempty"`
	// MessageThreshold holds the value of the "message_threshold" field.
	MessageThreshold int `json:"message_threshold,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// LastRunAt holds the value of the "last_run_at" field.
	LastRunAt time.Time `json:"last_run_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TimersQuery when eager-loading is set.
	Edges        TimersEdges `json:"edges"`
	user_timers  *uint64
	selectValues sql.SelectValues
}

// TimersEdges holds the relations/edges for other nodes in the graph.
type TimersEdges struct {
	// Users holds the value of the users edge.
	Users *User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimersEdges) UsersOrErr() (*User, error) {
	if e.Users != nil {
		return e.Users, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Timers) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case timers.FieldIsActive:
			values[i] = new(sql.NullBool)
		case timers.FieldID, timers.FieldIntervalSeconds, timers.FieldMessageThreshold:
			values[i] = new(sql.NullInt64)
		case timers.FieldName, timers.FieldMessage:
			values[i] = new(sql.NullString)
		case timers.FieldLastRunAt, timers.FieldCreatedAt, timers.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case timers.ForeignKeys[0]: // user_timers
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Timers fields.
func (_m *Timers) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case timers.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case timers.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case timers.FieldIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval_seconds", values[i])
			} else if value.Valid {
				_m.IntervalSeconds = int(value.Int64)
			}
		case timers.FieldMessageThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field message_threshold", values[i])
			} else if value.Valid {
				_m.MessageThreshold = int(value.Int64)
			}
		case timers.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case timers.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case timers.FieldLastRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_at", values[i])
			} else if value.Valid {
				_m.LastRunAt = value.Time
			}
		case timers.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case timers.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case timers.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_timers", value)
			} else if value.Valid {
				_m.user_timers = new(uint64)
				*_m.user_timers = uint64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Timers.
// This includes values selected through modifiers, order, etc.
func (_m *Timers) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Timers entity.
func (_m *Timers) QueryUsers() *UserQuery {
	return NewTimersClient(_m.config).QueryUsers(_m)
}

// Update returns a builder for updating this Timers.
// Note that you need to call Timers.Unwrap() before calling this method if this Timers
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Timers) Update() *TimersUpdateOne {
	return NewTimersClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Timers entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Timers) Unwrap() *Timers {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Timers is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Timers) String() string {
	var builder strings.Builder
	builder.WriteString("Timers(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("message_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageThreshold))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("last_run_at=")
	builder.WriteString(_m.LastRunAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TimersSlice is a parsable slice of Timers.
type TimersSlice []*Timers
