// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/predicate"
	"ItsBagelBot/internal/db/ent/tokens"
	"ItsBagelBot/internal/db/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TokensUpdate is the builder for updating Tokens entities.
type TokensUpdate struct {
	config
	hooks    []Hook
	mutation *TokensMutation
}

// Where appends a list predicates to the TokensUpdate builder.
func (_u *TokensUpdate) Where(ps ...predicate.Tokens) *TokensUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *TokensUpdate) SetType(v tokens.Type) *TokensUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TokensUpdate) SetNillableType(v *tokens.Type) *TokensUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *TokensUpdate) SetToken(v string) *TokensUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TokensUpdate) SetNillableToken(v *string) *TokensUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *TokensUpdate) SetRefreshToken(v string) *TokensUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *TokensUpdate) SetNillableRefreshToken(v *string) *TokensUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *TokensUpdate) ClearRefreshToken() *TokensUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *TokensUpdate) SetPlatform(v tokens.Platform) *TokensUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *TokensUpdate) SetNillablePlatform(v *tokens.Platform) *TokensUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *TokensUpdate) SetUsersID(id uint64) *TokensUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *TokensUpdate) SetUsers(v *User) *TokensUpdate {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the TokensMutation object of the builder.
func (_u *TokensUpdate) Mutation() *TokensMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *TokensUpdate) ClearUsers() *TokensUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TokensUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokensUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TokensUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokensUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokensUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := tokens.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tokens.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := tokens.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Tokens.platform": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tokens.users"`)
	}
	return nil
}

func (_u *TokensUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tokens.Table, tokens.Columns, sqlgraph.NewFieldSpec(tokens.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(tokens.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tokens.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(tokens.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(tokens.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(tokens.FieldPlatform, field.TypeEnum, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tokens.UsersTable,
			Columns: []string{tokens.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tokens.UsersTable,
			Columns: []string{tokens.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokens.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TokensUpdateOne is the builder for updating a single Tokens entity.
type TokensUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TokensMutation
}

// SetType sets the "type" field.
func (_u *TokensUpdateOne) SetType(v tokens.Type) *TokensUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *TokensUpdateOne) SetNillableType(v *tokens.Type) *TokensUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *TokensUpdateOne) SetToken(v string) *TokensUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *TokensUpdateOne) SetNillableToken(v *string) *TokensUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *TokensUpdateOne) SetRefreshToken(v string) *TokensUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *TokensUpdateOne) SetNillableRefreshToken(v *string) *TokensUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *TokensUpdateOne) ClearRefreshToken() *TokensUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *TokensUpdateOne) SetPlatform(v tokens.Platform) *TokensUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *TokensUpdateOne) SetNillablePlatform(v *tokens.Platform) *TokensUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_u *TokensUpdateOne) SetUsersID(id uint64) *TokensUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "users" edge to the User entity.
func (_u *TokensUpdateOne) SetUsers(v *User) *TokensUpdateOne {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the TokensMutation object of the builder.
func (_u *TokensUpdateOne) Mutation() *TokensMutation {
	return _u.mutation
}

// ClearUsers clears the "users" edge to the User entity.
func (_u *TokensUpdateOne) ClearUsers() *TokensUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// Where appends a list predicates to the TokensUpdate builder.
func (_u *TokensUpdateOne) Where(ps ...predicate.Tokens) *TokensUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TokensUpdateOne) Select(field string, fields ...string) *TokensUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tokens entity.
func (_u *TokensUpdateOne) Save(ctx context.Context) (*Tokens, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TokensUpdateOne) SaveX(ctx context.Context) *Tokens {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TokensUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TokensUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TokensUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := tokens.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tokens.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := tokens.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Tokens.platform": %w`, err)}
		}
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Tokens.users"`)
	}
	return nil
}

func (_u *TokensUpdateOne) sqlSave(ctx context.Context) (_node *Tokens, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tokens.Table, tokens.Columns, sqlgraph.NewFieldSpec(tokens.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tokens.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tokens.FieldID)
		for _, f := range fields {
			if !tokens.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tokens.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(tokens.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(tokens.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(tokens.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(tokens.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(tokens.FieldPlatform, field.TypeEnum, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tokens.UsersTable,
			Columns: []string{tokens.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tokens.UsersTable,
			Columns: []string{tokens.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tokens{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tokens.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
