// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/tokens"
	"ItsBagelBot/internal/db/ent/user"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Tokens is the model entity for the Tokens schema.
type Tokens struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Type holds the value of the "type" field.
	Type tokens.Type `json:"type,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"-"`
	// RefreshToken holds the value of the "refresh_token" field.
	RefreshToken string `json:"-"`
	// Platform holds the value of the "platform" field.
	Platform tokens.Platform `json:"platform,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TokensQuery when eager-loading is set.
	Edges        TokensEdges `json:"edges"`
	user_tokens  *uint64
	selectValues sql.SelectValues
}

// TokensEdges holds the relations/edges for other nodes in the graph.
type TokensEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TokensEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tokens) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tokens.FieldID:
			values[i] = new(sql.NullInt64)
		case tokens.FieldType, tokens.FieldToken, tokens.FieldRefreshToken, tokens.FieldPlatform:
			values[i] = new(sql.NullString)
		case tokens.ForeignKeys[0]: // user_tokens
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tokens fields.
func (_m *Tokens) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tokens.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tokens.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = tokens.Type(value.String)
			}
		case tokens.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case tokens.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				_m.RefreshToken = value.String
			}
		case tokens.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = tokens.Platform(value.String)
			}
		case tokens.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_tokens", value)
			} else if value.Valid {
				_m.user_tokens = new(uint64)
				*_m.user_tokens = uint64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tokens.
// This includes values selected through modifiers, order, etc.
func (_m *Tokens) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Tokens entity.
func (_m *Tokens) QueryUser() *UserQuery {
	return NewTokensClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this Tokens.
// Note that you need to call Tokens.Unwrap() before calling this method if this Tokens
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tokens) Update() *TokensUpdateOne {
	return NewTokensClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tokens entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tokens) Unwrap() *Tokens {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tokens is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tokens) String() string {
	var builder strings.Builder
	builder.WriteString("Tokens(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("refresh_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteByte(')')
	return builder.String()
}

// TokensSlice is a parsable slice of Tokens.
type TokensSlice []*Tokens
