// Code generated by ent, DO NOT EDIT.

package ent

import (
	"ItsBagelBot/internal/db/ent/tokens"
	"ItsBagelBot/internal/db/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TokensCreate is the builder for creating a Tokens entity.
type TokensCreate struct {
	config
	mutation *TokensMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *TokensCreate) SetType(v tokens.Type) *TokensCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *TokensCreate) SetNillableType(v *tokens.Type) *TokensCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *TokensCreate) SetToken(v string) *TokensCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *TokensCreate) SetRefreshToken(v string) *TokensCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_c *TokensCreate) SetNillableRefreshToken(v *string) *TokensCreate {
	if v != nil {
		_c.SetRefreshToken(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *TokensCreate) SetPlatform(v tokens.Platform) *TokensCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *TokensCreate) SetNillablePlatform(v *tokens.Platform) *TokensCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetUsersID sets the "users" edge to the User entity by ID.
func (_c *TokensCreate) SetUsersID(id uint64) *TokensCreate {
	_c.mutation.SetUsersID(id)
	return _c
}

// SetUsers sets the "users" edge to the User entity.
func (_c *TokensCreate) SetUsers(v *User) *TokensCreate {
	return _c.SetUsersID(v.ID)
}

// Mutation returns the TokensMutation object of the builder.
func (_c *TokensCreate) Mutation() *TokensMutation {
	return _c.mutation
}

// Save creates the Tokens in the database.
func (_c *TokensCreate) Save(ctx context.Context) (*Tokens, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TokensCreate) SaveX(ctx context.Context) *Tokens {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TokensCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TokensCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TokensCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := tokens.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Platform(); !ok {
		v := tokens.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TokensCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Tokens.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := tokens.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Tokens.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Tokens.token"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Tokens.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := tokens.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "Tokens.platform": %w`, err)}
		}
	}
	if len(_c.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "users", err: errors.New(`ent: missing required edge "Tokens.users"`)}
	}
	return nil
}

func (_c *TokensCreate) sqlSave(ctx context.Context) (*Tokens, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TokensCreate) createSpec() (*Tokens, *sqlgraph.CreateSpec) {
	var (
		_node = &Tokens{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tokens.Table, sqlgraph.NewFieldSpec(tokens.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(tokens.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(tokens.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(tokens.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(tokens.FieldPlatform, field.TypeEnum, value)
		_node.Platform = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tokens.UsersTable,
			Columns: []string{tokens.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TokensCreateBulk is the builder for creating many Tokens entities in bulk.
type TokensCreateBulk struct {
	config
	err      error
	builders []*TokensCreate
}

// Save creates the Tokens entities in the database.
func (_c *TokensCreateBulk) Save(ctx context.Context) ([]*Tokens, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tokens, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TokensMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TokensCreateBulk) SaveX(ctx context.Context) []*Tokens {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TokensCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TokensCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
